### ISSUE TITLE
Don't convert blocks that have a loot table assigned

### ISSUE THREAD

**Issue by BEMZ01** [Lauriichan/JustLootIt#20]
### Enhancement type

Feature

### Plugin version

1.7.1

### Describe what you want to request.

In one of my servers I have a feature that gives players chests with a loot table assigned through NBT. It would be great if there was an option to ignore any chests that a player places down that contains a loot table. 

Currently, if a player places a chest with a loot table inside it - the plugin will convert the chest and then the player can no longer break the block.

**Comment by Lauriichan** [comment]
This is definitely not vanilla behaviour.
What plugin are you using to give those blocks?

**Comment by Lauriichan** [comment]
The reason I am asking is that JLI doesn't convert blocks if a player placed them.
Only if it was placed through CustomStructures, BetterStructures or Structures placed using Vanilla methods.

**Comment by BEMZ01** [comment]
> ... long as they don't have OP and Creative as far as I am aware.

This would be the issue - I tested on a non-opped account and managed to place the loot chest down without issue. Sorry!
