### ISSUE TITLE
Loot chest not working.

### ISSUE THREAD

**Issue by nuttapillar** [Lauriichan/JustLootIt#26]
### Plugin version

1.8.3

### Plugin list

[14:23:59 INFO]: Paper Plugins: (1):
[14:23:59 INFO]:  - BKCommonLib
[14:23:59 INFO]: Bukkit Plugins: (88):
[14:23:59 INFO]:  - ajLeaderboards, ArcadeGames, AreaShop, BlueBorder, BlueBridgeCore, BlueBridgeGP, BlueBridgeWG, BlueMap, BlueMap-Essentials, BlueMapChatMarkers
[14:23:59 INFO]:  BlueMapDeathMarkers, BlueMapFloodgate, BMMarker, BungeeGuard, BungeeTabListPlus, ChatFeelings, ChestShop, ChestShopNotifier, ChestSort, Citizens
[14:23:59 INFO]:  CMILib, ConditionalEvents, ConsoleSpamFix, CoreProtect, DecentHolograms, Denizen, DiscordSRV, DtlPlayershops, dtlTradersPlus, EnderdragonManager
[14:23:59 INFO]:  Essentials, EssentialsChat, EssentialsSpawn, FarmControl, FarmingUpgrade, FastAsyncWorldEdit, FilteredHoppers, floodgate, Geyser-Spigot, GPFlags
[14:23:59 INFO]:  Interactions, InvUnload, JukeboxExtendedReborn, JustLootIt, LuckPerms, LWC, MiniMOTD, MyCommand, OpenInv, PlaceholderAPI
[14:23:59 INFO]:  ShulkerPacks, SkinsRestorer, sleep-most, Tebex, TimeIsMoney, Train_Carts, TreeAssist, Trivia, Vault, VeinMiner
[14:23:59 INFO]:  ViaBackwards, ViaVersion, ViewDistanceTweaks, Votifier, VotingPlugin, WorldEditSUI, WorldGuard, WorldGuardExtraFlags

### With what do you need help?

A player tried opening a loot chest, and it said they can't open it again, even though they hadn't been there before. So I got myself, an alt account, and a friend to try to open it, and we could open it, but it appeared empty for al of us. So I selected it with worldedit and did a /regen and then the area just filled with blocks. so I did undo, and it has reverted to a regular vanilla chest.
I tried standing on it and doing the container create command, but none of the types worked. kept saying no valid entity found

**Comment by nuttapillar** [comment]
Also, when doing the conversion, should I include vanilla chests? Or would that convert everyone's storage chests in their bases etc? It's a bit vague/confusing.

**Comment by nuttapillar** [comment]
im still confused though. I'm in a bastion, looking at one of several "loot inventory" named chests, all of which are empty. I tried using /jli container create entity static -1244 36 195 Ausworld_nether
and also just tried /jli container create entity static
and it always just says no valid entity
I'm not sure what to do to fix this.

**Comment by Lauriichan** [comment]
1. You have to break the container in order to remove
2. Static containers are containers which contents are saved, so if you leave it empty it will stay empty
3. The "container create entity" sub command is to create containers specifically on an entity, not a block.

If you can it would be great if you could join my discord so we can discuss things further there otherwise we can also continue here but communication on discord would probably be faster and easier

**Comment by nuttapillar** [comment]
So you want me to break the chest, put a new one there, and then run the create command?

**Comment by Lauriichan** [comment]
When creating a container you need to break the old container first if the block is a JLI container.
If not then you can just run the command, you usually don't want a static container but a vanilla instead.
So the command should look like this: "/jli container create vanilla -1244 36 195 Ausworld_nether", the coordinates and world are in theory not required as just looking at the block is enough.

**Comment by nuttapillar** [comment]
Strange though, when I tried to break the chest, it said it's a lot container. So why wasn't it acting like a loot container? 
Anyway I tried holding shift and breaking the chest, but it repeatedly says to break it again in the next 2 minutes to remove it. But no matter how many times I do this, within 2 minutes, it won't break.

**Comment by Lauriichan** [comment]
Please update your JLI

**Comment by Lauriichan** [comment]
I recommend running a migration conversion afterwards but that is not required

**Comment by nuttapillar** [comment]
Also I think we just found a bug in testing. There's a double-chest loot chest, and the loot is completely different depending on which side we click on to open the chest. So there's 2 different sets of loot.

**Comment by Lauriichan** [comment]
As I said, please update to the latest JLI version, thank you

**Comment by nuttapillar** [comment]
I've just downloaded the latest version, so I'll see how that goes after next reboot

**Comment by nuttapillar** [comment]
I updated to the latest version, and I was finally able to break the chest. But I still can't turn the vanilla chest into a fresh loot chest. I look at it and use the command, and it says no valid entities.

**Comment by Lauriichan** [comment]
> When creating a container you need to break the old container first if the block is a JLI container. If not then you can just run the command, you usually don't want a static container but a vanilla instead. So the command should look like this: "/jli container create vanilla -1244 36 195 Ausworld_nether", the coordinates and world are in theory not required as just looking at the block is enough.

I gave you an example here.

**Comment by nuttapillar** [comment]
ok so i stood on the chest, looked at it, and used /jli container create static -1245 36 197
it successfully linked, but the chest is empty. shouldnt it have fresh loot?

**Comment by Lauriichan** [comment]
As I said you before, the static container will just use the content of the chest.
If the chest is empty, the created container will also always be empty.
I told you to use the vanilla container type.

**Comment by nuttapillar** [comment]
Thanks. What should I enter as the loot table seed? Where can I find that?

**Comment by Lauriichan** [comment]
Any number you would like

**Comment by Lauriichan** [comment]
As long as you don't pick the same number and same loot table for the a chest, every chest will contain different loot.

**Comment by nuttapillar** [comment]
Interesting. I was trying a bunch of different numbers and letters etc, but
it kept saying it was invalid.

**Comment by nuttapillar** [comment]
I tried '12' and it accepted that, but now its asking for a key, whats that? I tried 12 again  but it says invalid loot table.

**Comment by nuttapillar** [comment]
Do you have a guide somewhere for all this? It doesn't seem very easy. Especially for someone new to all this.

**Comment by Lauriichan** [comment]
> I tried '12' and it accepted that, but now its asking for a key, whats that? I tried 12 again but it says invalid loot table.

Just the key of the loot table.

**Comment by Lauriichan** [comment]
> Do you have a guide somewhere for all this? It doesn't seem very easy. Especially for someone new to all this.

No there isn't I thought the guidance of the command itself would be enough especially because of the messages.
But apparently not, it's just a seed and the name of the loottable, there isn't more to it.

**Comment by Lauriichan** [comment]
If you don't know the name of the loot table that you want the chest to have then you have to find out somehow.
Maybe this website (first google result) may help you with that: https://mcreator.net/wiki/minecraft-vanilla-loot-tables-list
